Vagrant.configure(2) do |config|  
  config.vm.box= "debian/contrib-jessie64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/src"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    #Add the debian cross-toolchain repository
    apt-get install -y curl git vim
    echo "deb http://emdebian.org/tools/debian/ jessie main" > /etc/apt/sources.list.d/crosstools.list
    curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
    
    #Install the cross-compiler architecture
    sudo dpkg --add-architecture armhf
    sudo apt-get update
    apt-get install -y crossbuild-essential-armhf

    #Install deps for rootfs library building
    apt-get install -y proot qemu binfmt-support qemu-user-static

    #Get customised tegra scripts for L4T and setup environment
    echo "Setting up envinroment for tegra rootfs scripts and extracting L4T FS"
    cat /src/script_env.sh >> ~/.profile && source ~/.profile
    cd $TOP 
    git clone --branch l4t https://github.com/cphang99/tegra-rootfs-scripts.git scripts
    mkdir -p $TOP/out/target/arm/$DISTRO
    tar xpf /src/$L4T_FS -C $TOP/out/target/arm/$DISTRO

    #Prepare rootfs
    ./scripts/prepare-rootfs
    cd out/target/arm/$DISTRO/
    tar cpjf /home/l4tFS_prepared.tbz2 .
    cd $TOP
    cp l4tFS_prepared.tbz2 /src/
    echo "Preparation of rootfs complete!"
  SHELL
  
end
