Vagrant.configure(2) do |config|  
  config.vm.box= "debian/contrib-jessie64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/src"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    #Add the debian cross-toolchain repository
    apt-get install -y curl git vim
    echo "deb http://emdebian.org/tools/debian/ jessie main" > /etc/apt/sources.list.d/crosstools.list
    curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
    
    #Install the cross-compiler architecture
    sudo dpkg --add-architecture armhf
    sudo apt-get update
    apt-get install -y crossbuild-essential-armhf

    #Install deps for rootfs library building
    apt-get install -y proot qemu binfmt-support qemu-user-static
  SHELL
  
end
