Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "..", "/src"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    # Customize the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i

    #Add the debian cross-toolchain repository
    apt-get install -y curl git
    echo "deb http://emdebian.org/tools/debian/ jessie main" > /etc/apt/sources.list.d/crosstools.list
    curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -

    #Install the cross-compiler architecture
    sudo dpkg --add-architecture armhf
    sudo apt-get update
    apt-get install -y  crossbuild-essential-armhf

    sudo apt-get install -y autoconf automake 
    sudo apt-get install -y libtool libc6-i386 lib32stdc++6 lib32z1 pkg-config libwayland-dev bison flex bc 
    sudo apt-get install -y glib-2.0 libffi-dev xutils-dev python-mako intltool libxml2-dev

    git clone --branch "staging/work" https://github.com/Gnurou/nouveau.git
    git clone git://anongit.freedesktop.org/xcb/pthread-stubs
    git clone --branch "fb_modifiers" https://github.com/Gnurou/drm.git
    git clone --branch "tegra" https://github.com/Gnurou/mesa.git
    git clone --branch "fb_modifiers" git@github.com:Gnurou/kmscube.git
  SHELL

  
end
