
MESA_DEPS="libdrm-nouveau2:armhf 
libdrm2:armhf   
libelf-dev:armhf    
libelf1:armhf   
libexpat1-dev:armhf   
libllvm3.5:armhf   
libobjc-4.9-dev:armhf  
libobjc4:armhf   
libpciaccess0:armhf   
libtinfo-dev:armhf   
libudev-dev:armhf   
libvdpau-dev:armhf   
libvdpau1:armhf   
libx11-xcb-dev:armhf   
libxcb-dri2-0:armhf   
libxcb-dri2-0-dev:armhf   
libxcb-dri3-0:armhf   
libxcb-dri3-dev:armhf   
libxcb-glx0:armhf   
libxcb-glx0-dev:armhf   
libxcb-present-dev:armhf   
libxcb-present0:armhf   
libxcb-randr0:armhf   
libxcb-randr0-dev:armhf   
libxcb-render0:armhf   
libxcb-render0-dev:armhf   
libxcb-shape0:armhf   
libxcb-shape0-dev:armhf   
libxcb-sync-dev:armhf   
libxcb-sync1:armhf   
libxcb-xfixes0:armhf   
libxcb-xfixes0-dev:armhf   
libxdamage-dev:armhf   
libxdamage1:armhf   
libxfixes-dev:armhf   
libxfixes3:armhf   
libxshmfence-dev:armhf   
libxshmfence1:armhf   
x11proto-damage-dev:armhf   
x11proto-dri2-dev:armhf   
x11proto-dri3-dev:armhf   
x11proto-fixes-dev:armhf   
x11proto-gl-dev:armhf   
x11proto-present-dev:armhf   
binfmt-support:armhf
libssl-dev:armhf
libxxf86vm-dev:armhf
libxext-dev:armhf
libwayland-dev:armhf"

export MESA_DEPS

