Vagrant.configure(2) do |config|  
  config.vm.box= "debian/contrib-jessie64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "..", "/src"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    source /src/deploy_config
    /src/cross_compile_setup.sh  
   
    #Install deps for rootfs library building
    source /src/graphics_openstack/script_deps.sh
    sudo apt-get install -y $SCRIPT_DEPS

    #Get customised tegra scripts for L4T and setup environment
    echo "Setting up envinroment for tegra rootfs scripts and extracting L4T FS"
    cat /src/graphics_openstack/script_env.sh >> ~/.profile && source ~/.profile
    cd $TOP 
    git clone --branch l4t https://github.com/cphang99/tegra-rootfs-scripts.git scripts
    mkdir -p $TOP/out/target/arm/$DISTRO
    tar xpf /src/graphics_openstack/$L4T_FS -C $TOP/out/target/arm/$DISTRO

    #Prepare rootfs and get libraries
    ./scripts/prepare-rootfs
    /src/graphics_openstack/get_graphics_stack_packages.sh
    ./scripts/build-pthread-stubs
    ./scripts/build-drm
    ./scripts/build-mesa
    ./scripts/build-kmscube

    echo "Copying prepared rootfs to /src"
    cd out/target/arm/$DISTRO/
    tar cpjf /home/${PREPARED_ROOTFS_NAME} .
    cd $TOP
    cp ${PREPARED_ROOTFS_NAME} /src
    echo "Preparation of rootfs complete!"
  SHELL
  
end
