Vagrant.configure(2) do |config|  
  config.vm.box= "debian/contrib-jessie64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/src"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    #Add the debian cross-toolchain repository
    apt-get install -y curl git
    echo "deb http://emdebian.org/tools/debian/ jessie main" > /etc/apt/sources.list.d/crosstools.list
    curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
    
    #Install the cross-compiler architecture
    sudo dpkg --add-architecture armhf
    sudo apt-get update
    apt-get install -y crossbuild-essential-armhf

    #Install libraries used by all installations
    apt-get install -y autoconf automake 
    apt-get install -y libtool pkg-config bison flex bc 
    apt-get install -y glib-2.0 python-mako intltool

    #Clone the relevant libraries
    git clone git://anongit.freedesktop.org/xcb/pthread-stubs
    git clone --branch "fb_modifiers" https://github.com/Gnurou/drm.git
    git clone git://anongit.freedesktop.org/mesa/mesa
    git clone --branch "fb_modifiers" https://github.com/Gnurou/kmscube.git


  SHELL
  
end
