Vagrant.configure(2) do |config|  
  config.vm.box= "debian/contrib-jessie64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/src"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    #Add the debian cross-toolchain repository
    apt-get install -y curl git
    echo "deb http://emdebian.org/tools/debian/ jessie main" > /etc/apt/sources.list.d/crosstools.list
    curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
    
    #Install the cross-compiler architecture
    sudo dpkg --add-architecture armhf
    sudo apt-get update
    apt-get install -y crossbuild-essential-armhf

    #Install libraries used by all installations
    apt-get install -y autoconf automake 
    apt-get install -y libtool pkg-config bison flex bc 
    apt-get install -y glib-2.0 python-mako intltool xutils-dev

    #Clone the relevant libraries
    git clone git://anongit.freedesktop.org/xcb/pthread-stubs
    git clone git://anongit.freedesktop.org/mesa/drm
    git clone git://anongit.freedesktop.org/mesa/mesa
    git clone --branch "gk20a" https://github.com/Gnurou/kmscube.git
    
    #Source environment variables to .profile
    cat /src/nouveau-env.sh >> ~/.profile
    cat /src/mesa_deps.sh >> ~/.profile
    source ~/.profile
    
    #Build deps
    apt-get install -y $MESA_DEPS
    mkdir -p /home/vagrant/install

    #We need to use wayland scanner from native libwayland-dev (from ubuntu disto) but the armhf libaries from libwayland-dev:armhf
    wget http://launchpadlibrarian.net/188497486/libwayland-dev_1.6.0-2_amd64.deb
    mkdir libwayland-dev_amd64
    dpkg-deb -x libwayland-dev_1.6.0-2_amd64.deb libwayland-dev_amd64/
    cp libwayland-dev_amd64/usr/bin/wayland-scanner /usr/bin/

    #Make all your packages
    declare -a packages=("pthread-stubs" "drm" "mesa" "kmscube")
    for package in "${packages[@]}"
    do
       SETTINGS=""
       cd "$package"
       echo "building and installing $package"
       if [ $package = "drm" ];
       then 
            SETTINGS=$DRM_SETTINGS
       elif [ $package = "mesa" ];
       then
            SETTINGS=$MESA_SETTINGS
       fi
       /src/install_package.sh -h $HOST -p $NVD -s "$SETTINGS" -n 4
       cd ..
    done

    #Once built, adjust pkg-config paths
    cd $NVD/lib/pkgconfig
    sed -i 's|/home/vagrant/install|$DEST|g' *.pc
  SHELL
  
end
